-- 지방의회 설정
CREATE TABLE COLGOVER_SET (
    COLGOVER_SET_ID VARCHAR(100 BYTE) NOT NULL,
	RASMBLY_ID CHAR(6 BYTE) NOT NULL,
	RASMBLY_NM VARCHAR(100 BYTE) NOT NULL,
	ISVIEW CHAR(1 BYTE),
	SET_INTERVAL NUMBER,
	SYSTEM_STTUS_CODE CHAR(3 BYTE),
    SERVER VARCHAR(100 BYTE), /* '서버명'*/
    OS VARCHAR(100 BYTE),/* 'OS명'*/
    WAS VARCHAR(100 BYTE),/* 'WAS명'*/
    CPU VARCHAR(100 BYTE),/* 'CPU명'*/
    RAM VARCHAR(100 BYTE),/* 'RAM명'*/
    MODULE_INSTALL_PATH VARCHAR(1000 BYTE),/* '모듈설치경로'*/
    NOTE VARCHAR(4000 BYTE),/* '비고'*/
	CONSTRAINT COLGOVER_SET_PK PRIMARY KEY(COLGOVER_SET_ID, RASMBLY_ID)
);